name: Build

on:
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build exe
        run: |
          pyinstaller --onefile --windowed --name file-converter --icon resources/icons/app_icon.ico --add-data "resources;resources" main.py

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/file-converter.exe
